name: Generate Snake Activity Graph

on:
  schedule:
    # Eksekusi setiap 12 jam
    - cron: "0 */12 * * *"
  
  # Memungkinkan workflow ini dijalankan secara manual dari tab Actions
  workflow_dispatch:
  
  # Jalankan pada setiap push ke branch main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Step 1: Generasikan file animasi SVG snake dari kontribusi GitHub pengguna
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=58a6ff&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39
            dist/github-snake-dark.svg?color_snake=58a6ff&color_dots=#2d333b,#0e4429,#006d32,#26a641,#39d353

      # Step 2: Push animasi yang sudah dibuat ke branch "output"
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
